language: php
script: phpunit

php:
    - 5.3
    - 5.4
    - 5.5

before_script:
    - curl -s http://getcomposer.org/installer | php
    - wget http://get.influxdb.org/influxdb_0.9.0-rc17_amd64.deb
    - sudo dpkg -i influxdb_0.9.0-rc17_amd64.deb
    - travis_retry sudo service influxdb restart
    - php composer.phar install
